import { QuartzComponent, QuartzComponentConstructor } from "./types"

const BackgroundParticles: QuartzComponent = () => {
  return (
    <canvas
      id="bg-particles"
      aria-hidden="true"
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        pointerEvents: "none",
        zIndex: -1,
        opacity: 0.7,
      }}
    />
  )
}

BackgroundParticles.afterDOMLoaded = [
  "(function() {",
  "  const canvas = document.getElementById('bg-particles')",
  "  if (!canvas) return",
  "  const ctx = canvas.getContext('2d')",
  "  let particles = []",
  "  let w = window.innerWidth",
  "  let h = window.innerHeight",
  "  let mouse = { x: -1000, y: -1000 }",
  "  const colorsLight = ['#6a5a8a', '#a85a7a', '#7a6a9a', '#8a7a5a']",
  "  const colorsDark = ['#b8a8d8', '#d89ab8', '#c8b8e8', '#d8c898']",
  "  const isDarkTheme = function() {",
  "    return document.documentElement.getAttribute('saved-theme') === 'dark'",
  "  }",
  "  let colors = isDarkTheme() ? colorsDark : colorsLight",
  "  let lineColor = isDarkTheme() ? 'rgba(184, 168, 216, ' : 'rgba(106, 90, 138, '",
  "  const PARTICLE_COUNT = 90",
  "  const CONNECTION_DISTANCE = 120",
  "  const MOUSE_RADIUS = 180",
  "  const MOUSE_REPEL = 0.8",
  "  function resize() {",
  "    w = window.innerWidth",
  "    h = window.innerHeight",
  "    canvas.width = w",
  "    canvas.height = h",
  "  }",
  "  resize()",
  "  window.addEventListener('resize', resize)",
  "  window.addEventListener('mousemove', function(e) {",
  "    mouse.x = e.clientX",
  "    mouse.y = e.clientY",
  "  })",
  "  window.addEventListener('mouseleave', function() {",
  "    mouse.x = -1000",
  "    mouse.y = -1000",
  "  })",
  "  for (let i = 0; i < PARTICLE_COUNT; i++) {",
  "    particles.push({",
  "      x: Math.random() * w,",
  "      y: Math.random() * h,",
  "      vx: (Math.random() - 0.5) * 0.3,",
  "      vy: (Math.random() - 0.5) * 0.3,",
  "      r: Math.random() * 2.5 + 1.5,",
  "      color: colors[Math.floor(Math.random() * colors.length)],",
  "      alpha: Math.random() * 0.35 + 0.35,",
  "    })",
  "  }",
  "  function draw() {",
  "    ctx.clearRect(0, 0, w, h)",
  "    for (const p of particles) {",
  "      const dx = p.x - mouse.x",
  "      const dy = p.y - mouse.y",
  "      const dist = Math.sqrt(dx * dx + dy * dy)",
  "      if (dist < MOUSE_RADIUS && dist > 0) {",
  "        const force = (MOUSE_RADIUS - dist) / MOUSE_RADIUS * MOUSE_REPEL",
  "        p.vx += (dx / dist) * force * 0.1",
  "        p.vy += (dy / dist) * force * 0.1",
  "      }",
  "      p.x += p.vx",
  "      p.y += p.vy",
  "      p.vx *= 0.98",
  "      p.vy *= 0.98",
  "      if (Math.abs(p.vx) < 0.05) p.vx += (Math.random() - 0.5) * 0.1",
  "      if (Math.abs(p.vy) < 0.05) p.vy += (Math.random() - 0.5) * 0.1",
  "      if (p.x < 0) p.x = w",
  "      if (p.x > w) p.x = 0",
  "      if (p.y < 0) p.y = h",
  "      if (p.y > h) p.y = 0",
  "    }",
  "    for (let i = 0; i < particles.length; i++) {",
  "      for (let j = i + 1; j < particles.length; j++) {",
  "        const a = particles[i]",
  "        const b = particles[j]",
  "        const dx = a.x - b.x",
  "        const dy = a.y - b.y",
  "        const dist = Math.sqrt(dx * dx + dy * dy)",
  "        if (dist < CONNECTION_DISTANCE) {",
  "          const aNearMouse = Math.hypot(a.x - mouse.x, a.y - mouse.y) < MOUSE_RADIUS",
  "          const bNearMouse = Math.hypot(b.x - mouse.x, b.y - mouse.y) < MOUSE_RADIUS",
  "          if (aNearMouse || bNearMouse) {",
  "            const opacity = (1 - dist / CONNECTION_DISTANCE) * 0.25",
  "            ctx.strokeStyle = lineColor + opacity + ')'",
  "            ctx.lineWidth = 0.6",
  "            ctx.beginPath()",
  "            ctx.moveTo(a.x, a.y)",
  "            ctx.lineTo(b.x, b.y)",
  "            ctx.stroke()",
  "          }",
  "        }",
  "      }",
  "    }",
  "    for (const p of particles) {",
  "      const distToMouse = Math.hypot(p.x - mouse.x, p.y - mouse.y)",
  "      const highlight = distToMouse < MOUSE_RADIUS ? 0.5 : 0",
  "      ctx.globalAlpha = Math.min(1, p.alpha + highlight)",
  "      ctx.fillStyle = p.color",
  "      ctx.beginPath()",
  "      ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2)",
  "      ctx.fill()",
  "    }",
  "    ctx.globalAlpha = 1",
  "    requestAnimationFrame(draw)",
  "  }",
  "  const themeObserver = new MutationObserver(function() {",
  "    const next = isDarkTheme() ? colorsDark : colorsLight",
  "    lineColor = isDarkTheme() ? 'rgba(184, 168, 216, ' : 'rgba(106, 90, 138, '",
  "    colors = next",
  "    particles.forEach(function(p) {",
  "      p.color = next[Math.floor(Math.random() * next.length)]",
  "    })",
  "  })",
  "  themeObserver.observe(document.documentElement, {",
  "    attributes: true,",
  "    attributeFilter: ['saved-theme'],",
  "  })",
  "  draw()",
  "})()",
].join("\n")

export default (() => BackgroundParticles) satisfies QuartzComponentConstructor
